import { ListUsers } from 'shared/ui/test'
import { NotionAuthBtn } from 'shared'

export const metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App',
}

const Page = () => {
	return (
		<div className={'col justify-center align-middle'}>
			<div className={'flex justify-center p-2'}>
				<NotionAuthBtn />
			</div>
			{/*<ListUsers />*/}
		</div>
	)
}

export default Page
